version: "3"

services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8089:3000"

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: benchmark
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass

  adminer:
    image: adminer
    ports:
      - "8090:8080"
