version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: benchmark
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    networks:
      - store_network
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - store_network
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: always
    networks:
      - store_network
volumes:
  postgres:
networks:
  store_network:
    driver: bridge
    name: store_network