version: "3"
networks:
  default:
    name: benchmark
    external: false

services:
  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: benchmark
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data:rw

volumes:
  postgres:
